name: mina_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pedometer: ^4.1.1
  provider: ^6.1.5+1
  permission_handler: ^12.0.1
  http: ^1.6.0
  shared_preferences: ^2.5.5
  file_picker: ^8.1.4
  image_picker: ^1.2.2
  path_provider: ^2.1.5
  local_auth: ^3.0.1
  url_launcher: ^6.3.2
  flutter_local_notifications: ^21.0.0
  timezone: ^0.11.0
  workmanager: ^0.9.0
  fl_chart: ^1.2.0
  accurate_step_counter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - lib/images/logo.png
    - lib/images/google.png